#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Modified the Toxic Husky to a bit better one

echo '🏗️👷 Styling, testing and building your project before committing'

# Check Prettier standards
yarn check-format ||
(
    echo '🤢🤮🤢🤮 Your Styling does not match the styling guideline implemented 🤢🤮🤢🤮
            Prettier Check Failed. Run `yarn format`, add changes and try commit again.';
    false;
)

# Check ESLint Standards
yarn lint ||
(
        echo '😤🏀👋😤 Code Style does not match ESLint standards 😤🏀👋😤 
                ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false; 
)

# Check tsconfig standards
yarn check-types ||
(
    echo '🤡😂❌🤡 Failed Type check. 🤡😂❌🤡
            Make the changes required above.'
    false;
)

# If everything passes... Now we can commit
echo '🤔🤔🤔🤔... Alright.... Code looks good to me... Trying to build now. 🤔🤔🤔🤔'

yarn build ||
(
    echo '❌👷🔨❌ Better call Bob... Because your build failed ❌👷🔨❌
            Reactjs build failed: View the errors above to see why. 
    '
    false;
)

# If everything passes... Now we can commit
echo '✅✅✅✅ Committing now ✅✅✅✅'